class Solution:
    def slidingWindow(self, s: str, t: str) -> str:
        window = {}
        left, right = 0, 0
        while right < len(s):
            ...
            cur = ...
            window add...
            right += 1
            while left < right and window needs shrink:
                cur = ...
                window remove...
                left += 1
        return ...
